export type ListeningAlbum = {
  artist: string;
  title: string;
  image: string;
  detailsUrl: string;
  sourceUrl: string;
};

export const listeningAlbums: readonly ListeningAlbum[] = [
  {
    artist: "Def Leppard",
    title: "Hysteria",
    image: "/images/listening/def-leppard-hysteria.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Hysteria_(Def_Leppard_album)",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Def_Leppard_-_Hysteria_(vinyl_version).jpg",
  },
  {
    artist: "Nine Inch Nails",
    title: "Pretty Hate Machine",
    image: "/images/listening/nine-inch-nails-pretty-hate-machine.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Pretty_Hate_Machine",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Nine_Inch_Nails_-_Pretty_Hate_Machine.png",
  },
  {
    artist: "Journey",
    title: "Escape",
    image: "/images/listening/journey-escape.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Escape_(Journey_album)",
    sourceUrl: "https://en.wikipedia.org/wiki/File:JourneyEscapealbumcover.jpg",
  },
  {
    artist: "Chappell Roan",
    title: "The Rise and Fall of a Midwest Princess",
    image: "/images/listening/chappell-roan-the-rise-and-fall-of-a-midwest-princess.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/The_Rise_and_Fall_of_a_Midwest_Princess",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Chappell_Roan_-_The_Rise_and_Fall_of_a_Midwest_Princess.png",
  },
  {
    artist: "CHVRCHES",
    title: "The Bones of What You Believe",
    image: "/images/listening/chvrches-the-bones-of-what-you-believe.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/The_Bones_of_What_You_Believe",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Chvrches_-_The_Bones_of_What_You_Believe.png",
  },
  {
    artist: "Angelo Badalamenti",
    title: "Soundtrack from Twin Peaks",
    image: "/images/listening/angelo-badalamenti-soundtrack-from-twin-peaks.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Soundtrack_from_Twin_Peaks",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Soundtrack_From_Twin_Peaks.jpg",
  },
  {
    artist: "Talking Heads",
    title: "Remain in Light",
    image: "/images/listening/talking-heads-remain-in-light.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Remain_in_Light",
    sourceUrl: "https://en.wikipedia.org/wiki/File:TalkingHeadsRemaininLight.jpg",
  },
  {
    artist: "Kitarō",
    title: "Oasis",
    image: "/images/listening/kitaro-oasis.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Kitar%C5%8D_discography#Studio_albums",
    sourceUrl: "https://www.discogs.com/master/10527-Kitaro-%E5%96%9C%E5%A4%9A%E9%83%8E-Oasis",
  },
  {
    artist: "Queensrÿche",
    title: "Operation: Mindcrime",
    image: "/images/listening/queensryche-operation-mindcrime.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Operation:_Mindcrime",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Queensryche_-_Operation_Mindcrime_cover.jpg",
  },
  {
    artist: "Code Orange",
    title: "Underneath",
    image: "/images/listening/code-orange-underneath.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Underneath_(Code_Orange_album)",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Code_Orange_Underneath.jpg",
  },
  {
    artist: "Various Artists",
    title: "The Secret of My Success Soundtrack",
    image: "/images/listening/various-artists-the-secret-of-my-success-soundtrack.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/The_Secret_of_My_Success_(1987_film)#Soundtrack",
    sourceUrl: "https://www.discogs.com/master/114426-Various-The-Secret-Of-My-Success-Music-From-The-Motion-Picture-Soundtrack",
  },
  {
    artist: "Kanye West",
    title: "Yeezus",
    image: "/images/listening/kanye-west-yeezus.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Yeezus",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Yeezus_album_cover.png",
  },
  {
    artist: "Snow Patrol",
    title: "A Hundred Million Suns",
    image: "/images/listening/snow-patrol-a-hundred-million-suns.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/A_Hundred_Million_Suns",
    sourceUrl: "https://en.wikipedia.org/wiki/File:SnowPatrolAHMS.jpg",
  },
  {
    artist: "Forgotten Tomb",
    title: "Songs to Leave",
    image: "/images/listening/forgotten-tomb-songs-to-leave.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Forgotten_Tomb",
    sourceUrl: "https://officialforgottentomb.bandcamp.com/album/songs-to-leave",
  },
  {
    artist: "Dissection",
    title: "Storm of the Light’s Bane",
    image: "/images/listening/dissection-storm-of-the-lights-bane.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Storm_of_the_Light%27s_Bane",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Dissection_stormofthelightsbane.jpg",
  },
  {
    artist: "Styx",
    title: "Kilroy Was Here",
    image: "/images/listening/styx-kilroy-was-here.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Kilroy_Was_Here_(album)",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Styx_-_Kilroy_Was_Here.jpg",
  },
  {
    artist: "Our Lady Peace",
    title: "Spiritual Machines",
    image: "/images/listening/our-lady-peace-spiritual-machines.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Spiritual_Machines",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Our_Lady_Peace_-_Spiritual_Machines.png",
  },
  {
    artist: "Midnight Oil",
    title: "Diesel and Dust",
    image: "/images/listening/midnight-oil-diesel-and-dust.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Diesel_and_Dust",
    sourceUrl: "https://en.wikipedia.org/wiki/File:MidnightOil_DieselAndDust.jpg",
  },
  {
    artist: "Mercyful Fate",
    title: "Don’t Break the Oath",
    image: "/images/listening/mercyful-fate-dont-break-the-oath.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Don%27t_Break_the_Oath",
    sourceUrl: "https://en.wikipedia.org/wiki/File:MercyfulFateDBTO.jpg",
  },
  {
    artist: "Mercyful Fate",
    title: "Melissa",
    image: "/images/listening/mercyful-fate-melissa.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Melissa_(Mercyful_Fate_album)",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Melissa_album.png",
  },
  {
    artist: "Def Leppard",
    title: "Pyromania",
    image: "/images/listening/def-leppard-pyromania.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Pyromania_(album)",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Def_Leppard_-_Pyromania.jpg",
  },
  {
    artist: "Metal Church",
    title: "Metal Church",
    image: "/images/listening/metal-church-metal-church.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Metal_Church_(album)",
    sourceUrl: "https://en.wikipedia.org/wiki/File:MetalchurchselftitledAP.JPG",
  },
  {
    artist: "Metal Church",
    title: "The Dark",
    image: "/images/listening/metal-church-the-dark.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/The_Dark_(Metal_Church_album)",
    sourceUrl: "https://en.wikipedia.org/wiki/File:MetalChurch-TheDark.jpg",
  },
  {
    artist: "Judas Priest",
    title: "Painkiller",
    image: "/images/listening/judas-priest-painkiller.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Painkiller_(Judas_Priest_album)",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Judaspainkiller.JPG",
  },
  {
    artist: "Toto",
    title: "Toto IV",
    image: "/images/listening/toto-toto-iv.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Toto_IV",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Toto_Toto_IV.jpg",
  },
  {
    artist: "Pink Floyd",
    title: "The Wall",
    image: "/images/listening/pink-floyd-the-wall.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/The_Wall",
    sourceUrl: "https://en.wikipedia.org/wiki/File:PinkFloydWallCoverOriginalNoText.jpg",
  },
  {
    artist: "At the Gates",
    title: "Slaughter of the Soul",
    image: "/images/listening/at-the-gates-slaughter-of-the-soul.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Slaughter_of_the_Soul",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Slaughter_of_the_Soul.jpg",
  },
  {
    artist: "Sex Pistols",
    title: "Never Mind the Bollocks, Here’s the Sex Pistols",
    image: "/images/listening/sex-pistols-never-mind-the-bollocks.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Never_Mind_the_Bollocks,_Here%27s_the_Sex_Pistols",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Never_Mind_the_Bollocks,_Here%27s_the_Sex_Pistols.png",
  },
  {
    artist: "Guns N’ Roses",
    title: "Appetite for Destruction",
    image: "/images/listening/guns-n-roses-appetite-for-destruction.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Appetite_for_Destruction",
    sourceUrl: "https://en.wikipedia.org/wiki/File:GunsnRosesAppetiteforDestructionalbumcover.jpg",
  },
  {
    artist: "Ice-T",
    title: "O.G. Original Gangster",
    image: "/images/listening/ice-t-og-original-gangster.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/O.G._Original_Gangster",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Ice-T-O.G._Original_Gangster_(album_cover_with_matt).jpg",
  },
  {
    artist: "Timecop1983",
    title: "Night Drive",
    image: "/images/listening/timecop1983-night-drive.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Timecop1983",
    sourceUrl: "https://timecop1983.bandcamp.com/album/night-drive",
  },
  {
    artist: "Pearl Jam",
    title: "Ten",
    image: "/images/listening/pearl-jam-ten.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Ten_(Pearl_Jam_album)",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Pearl_Jam_Ten_Alt_Cover.jpg",
  },
  {
    artist: "Eyehategod",
    title: "Take as Needed for Pain",
    image: "/images/listening/eyehategod-take-as-needed-for-pain.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Take_as_Needed_for_Pain",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Eyehategod_-_Take_as_Needed_for_Pain.jpg",
  },
  {
    artist: "Jimmy Eat World",
    title: "Futures",
    image: "/images/listening/jimmy-eat-world-futures.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Futures_(album)",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Futues.jpg",
  },
  {
    artist: "Danny Brown",
    title: "Atrocity Exhibition",
    image: "/images/listening/danny-brown-atrocity-exhibition.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Atrocity_Exhibition_(album)",
    sourceUrl: "https://en.wikipedia.org/wiki/File:AtrocityExhibition.jpg",
  },
  {
    artist: "Roxette",
    title: "Look Sharp!",
    image: "/images/listening/roxette-look-sharp.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Look_Sharp!_(Roxette_album)",
    sourceUrl: "https://en.wikipedia.org/wiki/File:LookSharp.jpg",
  },
  {
    artist: "Swallow the Sun",
    title: "The Morning Never Came",
    image: "/images/listening/swallow-the-sun-the-morning-never-came.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/The_Morning_Never_Came",
    sourceUrl: "https://en.wikipedia.org/wiki/File:The_Morning_Never_Came.jpg",
  },
  {
    artist: "Beck",
    title: "Sea Change",
    image: "/images/listening/beck-sea-change.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Sea_Change_(album)",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Beckseachange.jpg",
  },
  {
    artist: "Garbage",
    title: "Version 2.0",
    image: "/images/listening/garbage-version-2-0.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Version_2.0",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Garbage_-_Version_2.0.png",
  },
  {
    artist: "The Cars",
    title: "The Cars",
    image: "/images/listening/the-cars-the-cars.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/The_Cars_(album)",
    sourceUrl: "https://en.wikipedia.org/wiki/File:The_Cars_-_The_Cars.png",
  },
  {
    artist: "Tori Amos",
    title: "Little Earthquakes",
    image: "/images/listening/tori-amos-little-earthquakes.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Little_Earthquakes",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Lecover-big.jpg",
  },
  {
    artist: "Mr. Bungle",
    title: "California",
    image: "/images/listening/mr-bungle-california.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/California_(Mr._Bungle_album)",
    sourceUrl: "https://en.wikipedia.org/wiki/File:MrBungle-California.jpg",
  },
  {
    artist: "Linkin Park",
    title: "Meteora",
    image: "/images/listening/linkin-park-meteora.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Meteora_(album)",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Linkin_Park_Meteora_Album_Cover.jpg",
  },
  {
    artist: "Linkin Park",
    title: "Hybrid Theory",
    image: "/images/listening/linkin-park-hybrid-theory.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Hybrid_Theory",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Linkin_Park_Hybrid_Theory_Album_Cover.jpg",
  },
  {
    artist: "Various Artists",
    title: "The Lost Boys: Original Motion Picture Soundtrack",
    image: "/images/listening/various-artists-the-lost-boys-soundtrack.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/The_Lost_Boys#Soundtrack",
    sourceUrl: "https://www.discogs.com/master/29208-Various-The-Lost-Boys-Original-Motion-Picture-Soundtrack",
  },
  {
    artist: "Billy Idol",
    title: "Rebel Yell",
    image: "/images/listening/billy-idol-rebel-yell.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Rebel_Yell_(album)",
    sourceUrl: "https://en.wikipedia.org/wiki/File:BillyIdolRebelYell.jpg",
  },
  {
    artist: "The Sisters of Mercy",
    title: "Floodland",
    image: "/images/listening/the-sisters-of-mercy-floodland.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Floodland_(album)",
    sourceUrl: "https://en.wikipedia.org/wiki/File:The_Sisters_of_Mercy_-_Floodland_cover_art.png",
  },
  {
    artist: "Heart",
    title: "Heart",
    image: "/images/listening/heart-heart.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Heart_(Heart_album)",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Heart_(Heart_album).png",
  },
  {
    artist: "blink-182",
    title: "Enema of the State",
    image: "/images/listening/blink-182-enema-of-the-state.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Enema_of_the_State",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Blink-182_-_Enema_of_the_State_cover.jpg",
  },
  {
    artist: "Various Artists",
    title: "Drive: Original Motion Picture Soundtrack",
    image: "/images/listening/various-artists-drive-original-motion-picture-soundtrack.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Drive_(soundtrack)",
    sourceUrl: "https://en.wikipedia.org/wiki/File:Drive_(soundtrack).jpg",
  },
] as const;
