export type ReadingBook = {
  author: string;
  title: string;
  detailsUrl: string;
  image?: string;
  sourceUrl?: string;
};

export const readingBooks: readonly ReadingBook[] = [
  {
    author: "Dan Millman",
    title: "Way of the Peaceful Warrior",
    image: "/images/reading/dan-millman-way-of-the-peaceful-warrior.webp",
    detailsUrl: "https://openlibrary.org/works/OL40816W/Way_of_the_peaceful_warrior",
    sourceUrl: "https://openlibrary.org/works/OL40816W/Way_of_the_peaceful_warrior",
  },
  {
    author: "Ayn Rand",
    title: "The Fountainhead",
    image: "/images/reading/ayn-rand-the-fountainhead.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/The_Fountainhead",
    sourceUrl: "https://openlibrary.org/works/OL731663W/The_Fountainhead",
  },
  {
    author: "Ayn Rand",
    title: "Atlas Shrugged",
    image: "/images/reading/ayn-rand-atlas-shrugged.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Atlas_Shrugged",
    sourceUrl: "https://openlibrary.org/works/OL731644W/Atlas_Shrugged",
  },
  {
    author: "Alexandre Dumas",
    title: "The Count of Monte Cristo",
    image: "/images/reading/alexandre-dumas-the-count-of-monte-cristo.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/The_Count_of_Monte_Cristo",
    sourceUrl: "https://openlibrary.org/works/OL36287W/The_Count_of_Monte_Cristo",
  },
  {
    author: "Stephen King",
    title: "Misery",
    image: "/images/reading/stephen-king-misery.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Misery_(novel)",
    sourceUrl: "https://openlibrary.org/works/OL81634W/Misery",
  },
  {
    author: "Reverend Wing F. Fing",
    title: "Fuck Yes!",
    image: "/images/reading/reverend-wing-f-fing-fuck-yes.webp",
    detailsUrl: "https://openlibrary.org/works/OL4959177W/Fuck_yes!",
    sourceUrl: "https://openlibrary.org/works/OL4959177W/Fuck_yes!",
  },
  {
    author: "Michael Brooks",
    title: "Instant Rapport",
    image: "/images/reading/michael-brooks-instant-rapport.webp",
    detailsUrl: "https://openlibrary.org/works/OL4484270W/Instant_Rapport",
    sourceUrl: "https://openlibrary.org/works/OL4484270W/Instant_Rapport",
  },
  {
    author: "Anthony Robbins",
    title: "Unlimited Power",
    image: "/images/reading/anthony-robbins-unlimited-power.webp",
    detailsUrl: "https://openlibrary.org/works/OL2715466W/Unlimited_power",
    sourceUrl: "https://openlibrary.org/works/OL2715466W/Unlimited_power",
  },
  {
    author: "Jean Hugard",
    title: "Card Manipulations",
    image: "/images/reading/jean-hugard-card-manipulations.webp",
    detailsUrl: "https://openlibrary.org/works/OL14906840W/Card_manipulations_series_1-5",
    sourceUrl: "https://openlibrary.org/works/OL14906840W/Card_manipulations_series_1-5",
  },
  {
    author: "William L. Livingston",
    title: "Have Fun at Work",
    image: "/images/reading/william-l-livingston-have-fun-at-work.webp",
    detailsUrl: "https://openlibrary.org/works/OL4489970W/Have_fun_at_work",
    sourceUrl: "https://openlibrary.org/works/OL4489970W/Have_fun_at_work",
  },
  {
    author: "Norman Stiles and Daniel Wilcox",
    title: "Grover and the Everything in the Whole Wide World Museum",
    image: "/images/reading/norman-stiles-daniel-wilcox-grover-museum.webp",
    detailsUrl: "https://books.google.com/books?id=BLY0AAAACAAJ",
    sourceUrl: "https://openlibrary.org/works/OL15852571W/Grover_and_the_Everything_in_the_Whole_Wide_World_Museum_featuring_lovable_furry_old_Grover",
  },
  {
    author: "Rudy Rucker",
    title: "The Fourth Dimension",
    image: "/images/reading/rudy-rucker-the-fourth-dimension.webp",
    detailsUrl: "https://www.rudyrucker.com/thefourthdimension/",
    sourceUrl: "https://openlibrary.org/works/OL115887W/The_Fourth_Dimension",
  },
  {
    author: "Ayn Rand",
    title: "Introduction to Objectivist Epistemology",
    image: "/images/reading/ayn-rand-introduction-to-objectivist-epistemology.webp",
    detailsUrl: "https://openlibrary.org/works/OL731723W/Introduction_to_Objectivist_Epistemology",
    sourceUrl: "https://openlibrary.org/works/OL731723W/Introduction_to_Objectivist_Epistemology",
  },
  {
    author: "Arthur Schopenhauer",
    title: "The World as Will and Representation",
    image: "/images/reading/arthur-schopenhauer-the-world-as-will-and-representation.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/The_World_as_Will_and_Representation",
    sourceUrl: "https://openlibrary.org/works/OL1183657W/Die_Welt_als_Wille_und_Vorstellung",
  },
  {
    author: "Don Turnbull (editor)",
    title: "Fiend Folio",
    image: "/images/reading/don-turnbull-fiend-folio.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Fiend_Folio",
    sourceUrl: "https://openlibrary.org/works/OL8066064W/Fiend_Folio",
  },
  {
    author: "Paula Taylor",
    title: "The Kids’ Whole Future Catalog",
    image: "/images/reading/paula-taylor-the-kids-whole-future-catalog.webp",
    detailsUrl: "https://books.google.com/books?id=2J62wY5ycQoC",
    sourceUrl: "https://openlibrary.org/works/OL4782907W/The_kids_whole_future_catalog",
  },
  {
    author: "Kim Schuette",
    title: "The Book of Adventure Games",
    image: "/images/reading/kim-schuette-the-book-of-adventure-games.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/The_Book_of_Adventure_Games",
    sourceUrl: "https://openlibrary.org/works/OL8672621W/The_Book_of_Adventure_Games",
  },
  {
    author: "Joel Whitburn",
    title: "Top Pop Albums, 1955–1996",
    image: "/images/reading/joel-whitburn-top-pop-albums-1955-1996.webp",
    detailsUrl: "https://openlibrary.org/works/OL706493W/Joel_Whitburns_top_pop_albums_1955-1996",
    sourceUrl: "https://openlibrary.org/works/OL706493W/Joel_Whitburns_top_pop_albums_1955-1996",
  },
  {
    author: "Dan Millman",
    title: "The Life You Were Born to Live",
    image: "/images/reading/dan-millman-the-life-you-were-born-to-live.webp",
    detailsUrl: "https://openlibrary.org/works/OL40815W/The_Life_You_Were_Born_to_Live",
    sourceUrl: "https://openlibrary.org/works/OL40815W/The_Life_You_Were_Born_to_Live",
  },
  {
    author: "Dr. John Lewis Lund",
    title: "How to Hug a Porcupine",
    image: "/images/reading/john-lewis-lund-how-to-hug-a-porcupine.webp",
    detailsUrl: "https://openlibrary.org/works/OL9273326W/How_to_Hug_a_Porcupine",
    sourceUrl: "https://openlibrary.org/works/OL9273326W/How_to_Hug_a_Porcupine",
  },
  {
    author: "Allen Newell",
    title: "Unified Theories of Cognition",
    image: "/images/reading/allen-newell-unified-theories-of-cognition.webp",
    detailsUrl: "https://openlibrary.org/works/OL4465101W/Unified_theories_of_cognition",
    sourceUrl: "https://openlibrary.org/works/OL4465101W/Unified_theories_of_cognition",
  },
  {
    author: "Falcon Travis",
    title: "The Spy’s Guidebook",
    image: "/images/reading/falcon-travis-the-spys-guidebook.webp",
    detailsUrl: "https://obnb.uk/p10106181-the-spys-guidebook",
    sourceUrl: "https://obnb.uk/p10106181-the-spys-guidebook",
  },
  {
    author: "Henry Miller",
    title: "Tropic of Cancer",
    image: "/images/reading/henry-miller-tropic-of-cancer.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Tropic_of_Cancer_(novel)",
    sourceUrl: "https://openlibrary.org/works/OL261866W/Tropic_of_Cancer",
  },
  {
    author: "George Orwell",
    title: "1984",
    image: "/images/reading/george-orwell-1984.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Nineteen_Eighty-Four",
    sourceUrl: "https://openlibrary.org/works/OL1168083W/Nineteen_Eighty-Four",
  },
  {
    author: "Miguel de Cervantes",
    title: "Don Quixote",
    image: "/images/reading/miguel-de-cervantes-don-quixote.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Don_Quixote",
    sourceUrl: "https://openlibrary.org/works/OL503666W/Don_Quijote_de_la_Mancha",
  },
  {
    author: "Joseph Heller",
    title: "Catch-22",
    image: "/images/reading/joseph-heller-catch-22.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Catch-22",
    sourceUrl: "https://openlibrary.org/works/OL276798W/Catch-22",
  },
  {
    author: "Kurt Vonnegut",
    title: "Breakfast of Champions",
    image: "/images/reading/kurt-vonnegut-breakfast-of-champions.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Breakfast_of_Champions",
    sourceUrl: "https://openlibrary.org/works/OL98488W/Breakfast_of_Champions",
  },
  {
    author: "Kurt Vonnegut",
    title: "Mother Night",
    image: "/images/reading/kurt-vonnegut-mother-night.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Mother_Night",
    sourceUrl: "https://openlibrary.org/works/OL98487W/Mother_Night",
  },
  {
    author: "Judy Blume",
    title: "Tiger Eyes",
    image: "/images/reading/judy-blume-tiger-eyes.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Tiger_Eyes",
    sourceUrl: "https://openlibrary.org/works/OL1838370W/Tiger_Eyes",
  },
  {
    author: "Immanuel Kant",
    title: "Critique of Pure Reason",
    image: "/images/reading/immanuel-kant-critique-of-pure-reason.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Critique_of_Pure_Reason",
    sourceUrl: "https://openlibrary.org/works/OL17104789W/Critique_of_Pure_Reason",
  },
  {
    author: "Jean-Paul Sartre",
    title: "Being and Nothingness",
    image: "/images/reading/jean-paul-sartre-being-and-nothingness.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Being_and_Nothingness",
    sourceUrl: "https://openlibrary.org/works/OL1161325W/Letre_et_le_neant",
  },
  {
    author: "G. W. F. Hegel",
    title: "Science of Logic",
    image: "/images/reading/g-w-f-hegel-science-of-logic.webp",
    detailsUrl: "https://en.wikipedia.org/wiki/Science_of_Logic",
    sourceUrl: "https://openlibrary.org/works/OL678564W/Wissenschaft_der_Logik",
  },
];
